const UPDATE_NEW_MESSAGE_BODY = "UPDATE-NEW-MESSAGE-BODY";
const SEND_MESSAGE = "SEND-MESSAGE";
const ADD_POST = "ADD_POST";
const UPDATE_NEW_POST_TEXT = "UPDATE-NEW-POST-TEXT";

export {
  UPDATE_NEW_MESSAGE_BODY,
  SEND_MESSAGE,
  ADD_POST,
  UPDATE_NEW_POST_TEXT,
};
